### ISSUE TITLE
Plan of Action / ToDo List

### ISSUE THREAD

**Issue by Neo-Desktop** [Neo-Desktop/WindowsXPKg#8]
In light of the recent exponential interest in this project @Endermanch and I have been working closely to help determine the best plan of action going forward.

My intention for this repository is to be a bit of a shared code base (if not eventually a shared library) that will do a significant part of the "heavy-lifting" for generating keys.

**The components of which will be as followed:** 

- [ ] Accurate PID generation based on product family
- [ ] ECDLP Signing from extracted and calculated keys [1]
- [x] A (somewhat) standardized method for storing the above values [(keys.json)](https://github.com/Neo-Desktop/WindowsXPKg/blob/master/keys.json)

---------

An additional project related to this is the **Telephone Activation** utility which will ultimately be included in this repository

- [ ] A port of the Telephone Activation utility to the command line (eventually as a library) for platform agnostic use
- [ ] An extension of the above utility to handle the various products (typically in the retail branch) that require activation

---------

One of my personal requirements for this code is to take a Linux first approach, we start small and work our way up, if platform specific needs arise, we will handle them one at a time.

**Thank you for your patience with us as we sort though everything and compare notes on our projects, we'll get things going shortly, the warm and positive repose from the community is all very overwhelming. **

--------

[1] NB: One of my personal gripes with how we're handling keys is that private keys must be recalculated from the inverse (*-K<sub>y</sub>*) of the public key or it is currently unusable to us. And while with modern machines this is more or less trivial to do, it doesn't *feel right* to me. There is a better way that is currently used by another keygen called `mskey4in1` and I find it imperative that I replicate whatever algorithm the programmer there used first.

The problem (and main blocker) here is that collectively those currently involved with this project are somewhat novices at Elliptic Cryptography, both your patience is requested and anyone with hints/tips/tricks that may be of assistance is more than welcome to get in touch with us.

**Comment by RobGlaze** [comment]
Hi,
I am having issues with compilation. Can I give an installation ID for someone to process for me while I work on sorting the compilation issues? Thanks for any help.

**Comment by thepwrtank18** [comment]
> Hi, I am having issues with compilation. Can I give an installation ID for someone to process for me while I work on sorting the compilation issues? Thanks for any help.

Check GitHub Actions for builds: https://github.com/Neo-Desktop/WindowsXPKg/actions
